export class Constants {
    static CHANNEL_INDIVIDUAL = 'INDIVIDUAL'
    static CHANNEL_TOPIC = 'TOPIC'
    static CHANNEL_GROUP = 'GROUP'
    static TYPE_DEPOSIT = 'PAYMENT'
    static EZYKARGO_REFERRER = 'EZYKARGO'
    static MAX_REFERRAL_CImMISSIONS = 100
    static MAX_REFERRAL_CIMMISSIONS_EZYOWNER = 50

}